# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 152d2837a368b029fbc0b021f6b144f51a72c17f66dd7198feb71dba88892de99c60beeb20875b20b936ded9cb80ba0903cf74e8d46ee46dc9093ce2dbca0d2b

test:
  secret_key_base: 948f25cc16e6d843a0e83d7f7325d05c47b35154916793dbd21eb4c48ff83ca45c8a4d83d22b1dad8a9738fe365141f7f06426e8f2220093ba8bf59517d11950

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
